run-name: Build Linux distributables
on: [ push, pull_request ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - run: rm node_modules/@julusian/jpeg-turbo/binding.gyp
      - name: Build artifacts
        run: npm run make
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opendeck-deb
          path: out/make/deb/x64
